version: "3.8"

services:
  fastapi:
    image: # PASTE AN INCOMING IMAGE
    volumes:
      - ./app_logs:/app/app.log
    command: ["python", "uvicorn_server.py"]
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: always
    ports:
      - "8080:8080" # порт 8080 для доступа извне
    networks:
      - internal_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432" # Открываем порт только для внутренней сети
    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge
